iLCSoft/Marlin

- .travis-ci.d/compile_and_test.sh
- .travis-ci.d/init_x86_64.sh
- .travis.yml
Now two builds are started on Travis one with gcc 6.2 and one with LLVM 3.9.
The two files:
- .travis-ci.d/compile_and_test.sh 
- .travis.yml 
are so generic now that they can be added without modification to any iLCSoft package.
> Add LLVM build to CI

- source/src/ProcessorMgr.cc
- Add possibility to use conditions also for eventModify processors. The processor setting the conditions must also run under modifyEvent!
> ProcessorMgr: enable checking of conditions for eventModifiers

- source/include/marlin/ProcessorEventSeeder.h
- source/src/ProcessorEventSeeder.cc
The loop over the map is not guaranteed to be constant across time or space so event seeds were not reproducible, because the order of the pointer to the processors depends on the memory.
Now use a vector with fixed order from processors calling to register themselves, which is constant.
- EventSeeder: make event seed truly constant in space and time
> EventSeeder: use vector of pairs to fix order of seeding processors

- source/include/marlin/CCProcessor.h
- source/include/marlin/CMProcessor.h
- source/include/marlin/IParser.h
- source/include/marlin/MarlinSteerCheck.h
- source/include/marlin/Parser.h
- source/include/marlin/Processor.h
- source/include/marlin/ProcessorMgr.h
- source/include/marlin/XMLParser.h
- source/src/CCProcessor.cc
- source/src/CMProcessor.cc
- source/src/Marlin.cc
- source/src/MarlinSteerCheck.cc
- source/src/Parser.cc
- source/src/Processor.cc
- source/src/ProcessorMgr.cc
- source/src/XMLParser.cc
- XMLParser: cleanup member objects, make StringParameters shared pointers to simplify ownership
Previously some were owned by the Processors, others were still owned by the XMLParser object
adapted interfaces
- Processors: functions using `StringParameter*` now use or return `shared_ptr<StringParameters>` instead
> Marlin parameter ownership cleanup

- doc/ReleaseNotes.md
- source/gui/addprocdialog.cpp
- source/gui/mainwindow.cpp
- adapt MarlinGUi to new usage of shared_ptr<StringParameters>
- remove duplicate entry in ReleaseNotes.md 
> adapt MarlinGUi to shared_ptr<StringParameters>

- source/include/marlin/XMLParser.h
- source/src/XMLParser.cc
- Added <include> element feature to read external xml file and replace in main Marlin steering file
- Added an include mechanism to the `XMLParser` class, allowing to load xml files into the main Marlin steering file. Note that :
- Nested includes will not be processed in the current version (include of include does not work)
- Exceptions are thrown if something goes wrong with the xml element (wrong name, no file, etc ...)
- Includes are processed iteratively in the document inside the root element.
> Include feature

- source/include/marlin/XMLParser.h
- source/src/Marlin.cc
- source/src/XMLParser.cc
- test/testmarlin/CMakeLists.txt
- test/testmarlin/base-eventmodifier.xml
- test/testmarlin/constants-eventmodifier.xml
- test/testmarlin/include-eventmodifier.xml
- Added a constants section in XMLParser parsing : 
- Allows to write constants and refer to in processor parameter values and global parameter values
- Makes use of ${constantName} to refer to a constant
- Use command line argument to override a constant
- example:
```xml
<constants>
<constant name="MCParticleCollection" value="MCParticle"/>
<constant name="FilePath" value="../../test/testmarlin"/>
<constant name="InputFile" value="${FilePath}/simjob.slcio"/>
</constants>
```
```shell
Marlin --constant.InputFile=aDifferentFile.slcio  marlin.xml
```
This has been tested with the test processor in the examples/mymarlin directory as for #19 .
Test it with this file : [marlin.txt](https://github.com/iLCSoft/Marlin/files/1329207/marlin.txt) (rename it with …
> Using constants in XML files

- source/include/marlin/IParser.h
- source/include/marlin/Parser.h
- source/include/marlin/XMLParser.h
- source/src/Marlin.cc
- source/src/Parser.cc
- source/src/XMLParser.cc
- test/testmarlin/base-eventmodifier.xml
- Added write() method to XMLParser (resp. Parser) to write the loaded xml tree (resp. same file) in a new file.
- Many methods adapted in XMLParser to make parameter/constant replacements persistent in the XML tree
- New global parameter "OutputSteeringFile" introduced to write down a new steering file after processing
- Added command line option -n for a Marlin dry-run
- Example : 
```shell
Marlin steeringFile.xml 
Marlin -n steeringFile.xml 
Marlin steeringFile.xml --global.OutputSteeringFile=MyParsedSteeringFile.xml 
```
> Dump post processed XML file

- source/src/XMLParser.cc
- Added constants replacement for condition attributes in the execute section
- Allows permanent conditions at runtime (not depending on processor return values)
- Allows to refer to constants in conditions in the execute section, e.g : 
```xml
<constants>
<constant name="RunOverlay" value="false" />
</constants>
<execute>
<if condition="${RunOverlay}">
<processor name="MyOverlayBg"/>
</if>
</execute>
```
and run : 
```shell
Marlin steering.xml --constant.RunOverlay=true
```
to change the behavior.
> Conditions with constants

- source/src/ProcessorMgr.cc
- remove exception thrown in ProcessorMgr::processRunHeader() if gear detector name is different from the one in the lcio file, and just warn the user
> Removed "hard" exception in ProcessorMgr::processRunHeader() 

- source/src/XMLParser.cc
- Added specific xml tree parsing to remove the output steering file name from the xml tree after parsing
- avoid to re-generate repeatably parsed steering files after a first parsing
> Output steering file fix

- source/src/XMLParser.cc
- XMLParsing: Replace constants in processor names: allows switching at initialisation time, e.g.:
```
<processor name="BeamCalReco${BCReco}"/>
```
and `Marlin --constant.BCReco=350GeV` to chose which BeamCalReco processor to run
> Processors with Constants

- source/src/ProcessorMgr.cc
When many bunch crossings are overlaid, or the IO is slow the modifyEvent can take quite a bit of time. 
- Also count the modifyEvent function in the processor running time information
> ProcessorMgr: time the modifyEvent function

- source/include/marlin/Parser.h
- source/include/marlin/XMLParser.h
- source/src/Marlin.cc
allows for changing LCFIPlus like parameters on command line
This would solve this problem lcfiplus/lcfiplus#3 without invalidating all the existing XML files. As there are additional checks that parameter names are in the XML file
- Marlin command line arguments: parameter names may now contain dots, solves lcfiplus/lcfiplus#3
- LCTokenizer: add optional max parameter to limit the number of resulting tokens
> allow parameters with dots to be changed on command line

- source/src/XMLParser.cc
- XMLParser: Fix "random" crash during XML parsing. Depends on XML Steering file and memory runtime behaviour, when some freed memory is overwritten
```
/Marlin/source/tinyxml/src/tinyxml.cc:377: const TiXmlNode* TiXmlNode::IterateChildren(const char*, const TiXmlNode*) const: Assertion `previous->parent == this' failed.
```
- XMLParser: Fix "invalid read errors" reported by valgrind. Objects were removed before they were used again, which probably lead to the above mentioned crashs
The crash can (maybe?) be reproduced with attached steering file (renamed to xml)
[break.txt](https://github.com/iLCSoft/Marlin/files/3013507/break.txt)
```
source /cvmfs/clicdp.cern.ch/iLCSoft/builds/2019-02-20/x86_64-slc6-gcc62-opt/init_ilcsoft.sh
wget …
```
> fix "invalid read" errors from valgrind, prevent crash in XML parsing

- source/include/marlin/EventSelector.h
- source/include/marlin/Processor.h
These changes are needed to configure and run Marlin processors from a Gaudi Algorithm or avoid a clash in the naming of the EventSelector class
- Marlin::Processor: make setParameters and setName public functions
- Marlin::EventSelector: moved to marlin namespace
> For Wrapping processors inside Gaudi

- source/include/marlin/LCIOOutputProcessor.h
- source/src/LCIOOutputProcessor.cc
- Set LCIO output compression to ON by default, and compression level to 6 (ZLIB default)
> Fix LCIO output compression level

- source/include/jenkinsHash.h
- source/src/ConditionsProcessor.cc
- source/src/ProcessorMgr.cc
- source/src/XMLParser.cc
- test/marlintest/include/TestCommentParsingProcessor.h
- test/marlintest/src/TestCommentParsingProcesser.cc
- test/marlintest/src/TestProcessorEventSeeder.cc
- test/testmarlin/CMakeLists.txt
- test/testmarlin/parse_steering_comments.xml
- Fix #43, a bug where xml comment fields were processed as a legitimate values and shadowed any data that comes after the comment.
___
**steer.xml**
```xml
<parameter name="LCIOInputFiles">
data_test1.slcio
data_test2.slcio
data_test3.slcio
</parameter>
```
**Before PR:**
```
***********************************************
A runtime error occured - (uncaught exception):
/cvmfs/ilc.desy.de/sw/x86_64_gcc82_centos7/v02-02-03/lcio/v02-17/src/cpp/src/MT/LCReader.cc (l.49) in open: Couldn't open input stream 'test_comment' [not_open]
Marlin will have to be terminated, sorry.
***********************************************
```
**After PR:**
```
LCIO Input Files:
data_test1.slcio
data_test2.slcio
data_test3.slcio
```
___
**steer.xml**
```xml
<parameter …
```
> Fix shadowing proper parameter values by the xml comments elements

- source/include/marlin/Processor.h
- Add a `MarlinWrapperPrivateAccessor` class that allows the `MarlinProcessorWrapper` to access private methods by constructing such a class on the fly, when necessary.
> Add accessor class for wrapper to allow private method access

- source/include/marlin/PatchCollections.h
- source/src/PatchCollections.cc
- Add a simple processor `PatchCollections` that can patch missing collections in LCIO events by adding empty collections to these events
-  needs https://github.com/iLCSoft/LCIO/pull/158
> Patch missing collections  

- .github/workflows/key4hep.yml
- .github/workflows/linux.yml
- Switch to latest clicdp nightlies for CI
- Update Key4hep CI workflows to run on releases and nightlies (including c++20)
> Update CI workflows

- source/src/XMLParser.cc
- Allow to have empty constant values in steering files and only throw if there really is no constant specified.
This is an alternative to https://github.com/iLCSoft/ILDConfig/pull/136 and I also think this should be the intended behavior.
> Allow to empty constant values

- .github/workflows/key4hep.yml
- source/include/marlin/EventModifier.h
- Make sure that all names that are used by `EventModifier` are forward declared
- Add missing include to make `EventModifier` usable without having to re-order includes
- Update the key4hep based github action workflows to use supported OSs
Uncovered by CI in https://github.com/iLCSoft/MarlinTrkProcessors/pull/70
> Make sure all used names have been declared

- CMakeLists.txt
- Add LANGUAGES CXX to the top level CMakeLists.txt to disable checks for a C compiler
> Add LANGUAGES CXX to the top level CMakeLists.txt
